let eEnglishInput = document.getElementById('english-input');
// let eBtnTranslate = document.getElementById('btn-translate');
let eresult = document.getElementById('result');
let eData = [
    " Từ",
    "A",
    "– able (adj)",
    "– abandon (v)",
    "– about (adv)",
    "– above (adv)",
    "– act (n, v)",
    "– add (v)",
    "– afraid (adj)",
    "– after (adv)",
    "– again (adv)",
    "– against (prep)",
    "– age (n)",
    "– ago (adv)",
    "– agree (v)",
    "– air (n)",
    "– all (det, pron, adv)",
    "– allow (v)",
    "– also (adv)",
    "– always (adv)",
    "– among (prep)",
    "– an",
    "– and (conj)",
    "– anger (n)",
    "– animal (n)",
    "– answer (n, v)",
    "– any (det, pron, adv)",
    "– appear (v)",
    "– apple (n)",
    "– are",
    "– area (n)",
    "– arm (n, v)",
    "– arrange (v)",
    "– arrive (v (+at in))",
    "– art (n)",
    "– as (prep, adv, conj)",
    "– ask (v)",
    "– at (prep)",
    "– atom (n)",
    "",
    "B",
    "– baby (n)",
    "– back (n, adj, adv, v)",
    "– bad (adj)",
    "– ball (n)",
    "– band (n)",
    "– bank (n)",
    "– bar (n)",
    "– base (n, v)",
    "– basic (adj)",
    "– bat (n)",
    "– be (v)",
    "– bear (v)",
    "– beat (n, v)",
    "– beauty (n)",
    "– bed (n)",
    "– been (v)",
    "– before (prep, conj, adv)",
    "– began (v)",
    "– begin (v)",
    "– behind (prep, adv)",
    "– believe (v)",
    "– bell (n)",
    "– best (adj)",
    "– better (adj)",
    "– between (prep, adv)",
    "– big (adj)",
    "– bird (n)",
    "– bit (n)",
    "– black (adj, n)",
    "– block (n, v)",
    "– blood (n)",
    "– blow (v, n)",
    "– blue (adj, n)",
    "– board (n, v)",
    "– boat (n)",
    "– body (n)",
    "– bone (n)",
    "– book (n, v)",
    "– born (v)",
    "– both (det, pron)",
    "– bottom (n, adj)",
    "– bought (v)",
    "– box (n)",
    "– boy (n)",
    "– branch (n)",
    "– bread (n)",
    "– break (v, n)",
    "– bright (adj)",
    "– bring (v)",
    "– broad (adj)",
    "– broke (v)",
    "– brother (n)",
    "– brought (v)",
    "– brown (adj, n)",
    "– build (v)",
    "– burn (v)",
    "– busy (adj)",
    "– but (conj)",
    "– buy (v)",
    "– by (prep, adv)",
    "",
    "C",
    "– call (v, n)",
    "– came (v)",
    "– camp (n, v)",
    "– can (modal v, n)",
    "– capital (n, adj)",
    "– captain (n)",
    "– car (n)",
    "– card (n)",
    "– care (n, v)",
    "– carry (v)",
    "– case (n)",
    "– cat (n)",
    "– catch (v)",
    "– caught (v)",
    "– cause (n, v)",
    "– cell (n)",
    "– cent (n)",
    "– center (từ Mỹ,nghĩa Mỹ)",
    "– century (n)",
    "– certain (adj, pron)",
    "– chair (n)",
    "– chance (n)",
    "– change (v, n)",
    "– character (n)",
    "– charge (n, v)",
    "– chart (n, v)",
    "– check (v, n)",
    "– chick (n)",
    "– chief (adj, n)",
    "– child (n)",
    "– children (n)",
    "– choose (v)",
    "– chord",
    "– circle (n)",
    "– city (n)",
    "– claim (v, n)",
    "– class (n)",
    "– clean (adj, v)",
    "– clear (adj, v)",
    "– climb (v)",
    "– clock (n)",
    "– close (adj, v)",
    "– clothe",
    "– cloud (n)",
    "– coast (n)",
    "– coat (n)",
    "– cold (adj, n)",
    "– collect (v)",
    "– colony (n)",
    "– color (n)",
    "– column (n)",
    "– come (v)",
    "– common (adj)",
    "– company (n)",
    "– compare (v)",
    "– complete (adj, v)",
    "– condition (n)",
    "– connect (v)",
    "– consider (v)",
    "– consonant",
    "– contain (v)",
    "– continent (n)",
    "– continue (v)",
    "– control (n, v)",
    "– cook (v, n)",
    "– cool (adj, v)",
    "– copy (n, v)",
    "– corn",
    "– corner (n)",
    "– correct (adj, v)",
    "– cost (n, v)",
    "– cotton (n)",
    "– could (v)",
    "– count (v)",
    "– country (n)",
    "– course (n)",
    "– cover (v, n)",
    "– cow (n)",
    "– crease",
    "– create (v)",
    "– crop (n)",
    "– cross (n, v)",
    "– crowd (n)",
    "– cry (v, n)",
    "– current (adj, n)",
    "– cut (v, n)",
    "",
    "D",
    "– dad (n)",
    "– dance (n, v)",
    "– danger (n)",
    "– dark (adj, n)",
    "– day (n)",
    "– dead (adj)",
    "– deal (v, n)",
    "– dear (adj)",
    "– death (n)",
    "– decide (v)",
    "– decimal",
    "– deep (adj, adv)",
    "– degree (n)",
    "– depend (+ on, upon)",
    "– describe (v)",
    "– desert (n, v)",
    "– design (n, v)",
    "– determine (v)",
    "– develop (v)",
    "– dictionary (n)",
    "– die (v)",
    "– differ ((thường) + from)",
    "– difficult (adj)",
    "– direct (adj, v)",
    "– discuss (v)",
    "– distant",
    "– divide (v)",
    "– division (n)",
    "– do (v)",
    "– doctor (n)",
    "– does (v)",
    "– dog (n)",
    "– dollar (n)",
    "– done",
    "– door (n)",
    "– double (adj, det, adv, v)",
    "– down (adv, prep)",
    "– draw (v)",
    "– dream (n, v)",
    "– dress (n, v)",
    "– drink (n, v)",
    "– drive (v, n)",
    "– drop (v, n)",
    "– dry (adj, v)",
    "– duck (n)",
    "– during (prep)",
    "E",
    "– each (det, pron)",
    "– ear (n)",
    "– early (adj, adv)",
    "– earth (n)",
    "– ease (n, v)",
    "– east (n, adj, adv)",
    "– eat (v)",
    "– edge (n)",
    "– effect (n)",
    "– egg (n)",
    "– eight",
    "– either (det, pron, adv)",
    "– electric (adj)",
    "– element (n)",
    "– else (adv)",
    "– end (n, v)",
    "– enemy (n)",
    "– energy (n)",
    "– engine (n)",
    "– enough (det, pron, adv)",
    "– enter (v)",
    "– equal (adj, n, v)",
    "– equate",
    "– especially (adv)",
    "– even (adv, adj)",
    "– evening (n)",
    "– event (n)",
    "– ever (adv)",
    "– every (det)",
    "– exact (adj)",
    "– example (n)",
    "– except (prep, conj)",
    "– excite (v)",
    "– exercise (n, v)",
    "– expect (v)",
    "– experience (n, v)",
    "– experiment (n, v)",
    "– eye (n)",
    "",
    "F",
    "– face (n, v)",
    "– fact (n)",
    "– fair (adj)",
    "– fall (v, n)",
    "– family (n, adj)",
    "– famous (adj)",
    "– far (adv, adj)",
    "– farm (n)",
    "– fast (adj, adv)",
    "– fat (adj, n)",
    "– father (n)",
    "– favor",
    "– fear (n, v)",
    "– feed (v)",
    "– feel (v)",
    "– feet (n)",
    "– fell (v)",
    "– felt (v)",
    "– few (det, adj, pron)",
    "– field (n)",
    "– fig (n)",
    "– fight (v, n)",
    "– figure (n, v)",
    "– fill (v)",
    "– final (adj, n)",
    "– find (v)",
    "– fine (adj)",
    "– finger (n)",
    "– finish (v, n)",
    "– fire (n, v)",
    "– first (det)",
    "– fish (n, v)",
    "– fit (v, adj)",
    "– five",
    "– flat (adj, n)",
    "– floor (n)",
    "– flow (n, v)",
    "– flower (n)",
    "– fly (v, n)",
    "– follow (v)",
    "– food (n)",
    "– foot (n)",
    "– for (prep)",
    "– force (n, v)",
    "– forest (n)",
    "– form (n, v)",
    "– forward (adv, adj)",
    "– found (v)",
    "– four",
    "– fraction",
    "– free (adj, v, adv)",
    "– fresh (adj)",
    "– friend (n)",
    "– from (prep)",
    "– front (n, adj)",
    "– fruit (n)",
    "– full (adj)",
    "– fun (n, adj)",
    "",
    "G",
    "– game (n)",
    "– garden (n)",
    "– gas (n)",
    "– gather (v)",
    "– gave (v)",
    "– general (adj)",
    "– gentle (adj)",
    "– get (v)",
    "– girl (n)",
    "– give (v)",
    "– glad (adj)",
    "– glass (n)",
    "– go (v)",
    "– gold (n, adj)",
    "– gone",
    "– good (adj, n)",
    "– got (v)",
    "– govern (v)",
    "– grand (adj)",
    "– grass (n)",
    "– gray (adj, v, n)",
    "– great (adj)",
    "– green (adj, n)",
    "– grew (v)",
    "– ground (n)",
    "– group (n)",
    "– grow (v)",
    "– guess (v, n)",
    "– guide (n, v)",
    "– gun (n)",
    "",
    "H",
    "– had (v)",
    "– hair (n)",
    "– half (n, det, pron, adv)",
    "– hand (n, v)",
    "– happen (v)",
    "– happy (adj)",
    "– hard (adj, adv)",
    "– has",
    "– hat (n)",
    "– have (v, auxiliary v)",
    "– he (pron)",
    "– head (n, v)",
    "– hear (v)",
    "– heard (v)",
    "– heart (n)",
    "– heat (n, v)",
    "– heavy (adj)",
    "– held (v)",
    "– help (v, n)",
    "– her (pron, det)",
    "– here (adv)",
    "– high (adj, adv)",
    "– hill (n)",
    "– him (pron)",
    "– his (det, pron)",
    "– history (n)",
    "– hit (v, n)",
    "– hold (v, n)",
    "– hole (n)",
    "– home (n, adv)",
    "– hope (v, n)",
    "– horse (n)",
    "– hot (adj)",
    "– hour (n)",
    "– house (n)",
    "– how (adv)",
    "– huge (adj)",
    "– human (adj, n)",
    "– hundred",
    "– hunt (v)",
    "– hurry (v, n)",
    "",
    "I",
    "– I (n)",
    "– ice (n)",
    "– idea (n)",
    "– if (conj)",
    "– imagine (v)",
    "– in (prep, adv)",
    "– inch (n)",
    "– include (v)",
    "– indicate (v)",
    "– industry (n)",
    "– insect (n)",
    "– instant (adj)",
    "– instrument (n)",
    "– interest (n, v)",
    "– invent (v)",
    "– iron (n, v)",
    "– is",
    "– island (n)",
    "– it (pron, det)",
    "",
    "J",
    "– job (n)",
    "– join (v)",
    "– joy (n)",
    "– jump (v, n)",
    "– just (adv)",
    "",
    "K",
    "– keep (v)",
    "– kept (v)",
    "– key (n, adj)",
    "– kill (v)",
    "– kind (n, adj)",
    "– king (n)",
    "– knew",
    "– know (v)",
    "",
    "L",
    "– lady (n)",
    "– lake (n)",
    "– land (n, v)",
    "– language (n)",
    "– large (adj)",
    "– last (det, adv, n, v)",
    "– late (adj, adv)",
    "– laugh (v, n)",
    "– law (n)",
    "– lay (v)",
    "– lead (v, n)",
    "– learn (v)",
    "– least (det, pron, adv)",
    "– leave (v)",
    "– led (v)",
    "– left (adj, adv, n)",
    "– leg (n)",
    "– length (n)",
    "– less (det, pron, adv)",
    "– let (v)",
    "– letter (n)",
    "– level (n, adj)",
    "– lie (v, n)",
    "– life (n)",
    "– lift (v, n)",
    "– light (n, adj, v)",
    "– like (prep, v, conj)",
    "– line (n)",
    "– liquid (n, adj)",
    "– list (n, v)",
    "– listen (v)",
    "– little (adj, det, pron, adv)",
    "– live (v)",
    "– locate (v)",
    "– log",
    "– lone",
    "– long (adj, adv)",
    "– look (v, n)",
    "– lost (adj)",
    "– lot (n)",
    "– loud (adj, adv)",
    "– love (adj)",
    "– low (adj, adv)",
    "",
    "M",
    "– machine (n)",
    "– made (v)",
    "– magnet (n)",
    "– main (adj)",
    "– major (adj)",
    "– make (v, n)",
    "– man (n)",
    "– many (det, pron)",
    "– map (n)",
    "– mark (n, v)",
    "– market (n)",
    "– mass (n, adj)",
    "– master (n.)",
    "– match (n, v)",
    "– material (n, adj)",
    "– matter (n, v)",
    "– may (n)",
    "– me (pron)",
    "– mean (v)",
    "– meant",
    "– measure (v, n)",
    "– meat (n)",
    "– meet (v)",
    "– melody",
    "– men (n)",
    "– metal (n)",
    "– method (n)",
    "– middle (n, adj)",
    "– might (modal v)",
    "– mile (n)",
    "– milk (n)",
    "– million",
    "– mind (n, v)",
    "– mine (pron, n)",
    "– minute (n)",
    "– miss (n)",
    "– mix (v, n)",
    "– modern (adj)",
    "– molecule",
    "– moment (n)",
    "– money (n)",
    "– month (n)",
    "– moon (n)",
    "– more (det, pron, adv)",
    "– morning (n.)",
    "– most (det, pron, adv)",
    "– mother (n)",
    "– motion (n)",
    "– mount (v, n)",
    "– mountain (n)",
    "– mouth (n)",
    "– move (v, n)",
    "– much (det, pron, adv)",
    "– multiply (v)",
    "– music (n)",
    "– must (modal v)",
    "– my (det)",
    "",
    "N",
    "– name (n, v)",
    "– nation (n)",
    "– natural (adj)",
    "– nature (n)",
    "– near (adj, adv, prep)",
    "– necessary (adj)",
    "– neck (n)",
    "– need (v, modal v, n)",
    "– neighbor (n)",
    "– never (adv)",
    "– new (adj)",
    "– next (adj, adv, n)",
    "– night (n)",
    "– nine",
    "– no (det)",
    "– noise (n)",
    "– noon (n)",
    "– nor (conj, adv)",
    "– north (n, adj, adv)",
    "– nose (n)",
    "– note (n, v)",
    "– nothing (pron)",
    "– notice (n, v)",
    "– noun (ngôn ngữ học)",
    "– now (adv)",
    "– number (n)",
    "-numeral (thuộc)",
    "",
    "O",
    "– object  (n, v)",
    "– observe (v)",
    "– occur (v)",
    "– ocean (n)",
    "– of (prep)",
    "– off (adv, prep)",
    "– offer (v, n)",
    "– office (n)",
    "– often (adv)",
    "– oh (exclamation)",
    "– oil (n)",
    "– old (adj)",
    "– on (prep, adv)",
    "– once (adv, conj)",
    "– one (number, det, pron)",
    "– only (adj, adv)",
    "– open (adj, v)",
    "– operate (v)",
    "– opposite (adj, adv, n, prep)",
    "– or",
    "– order (n, v)",
    "– organ (n)",
    "– original (adj, n)",
    "– other (adj, pron)",
    "– our (det)",
    "– out (adv)",
    "– over (adv, prep)",
    "– own (adj, pron, v)",
    "– oxygen (hoá học)",
    "",
    "P",
    "– page (n (abbr p))",
    "– paint (n, v)",
    "– pair (n)",
    "– paper (n)",
    "– paragraph (n)",
    "– parent (n)",
    "– part (n)",
    "– particular (adj)",
    "– party (n)",
    "– pass (v)",
    "– past (adj, n, prep, adv)",
    "– path (n)",
    "– pattern (n)",
    "– pay (v, n)",
    "– people (n)",
    "– perhaps (adv)",
    "– period (n)",
    "– person (n)",
    "– phrase (n)",
    "– pick (v)",
    "– picture (n)",
    "– piece (n)",
    "– pitch (n)",
    "– place (n, v)",
    "– plain (adj)",
    "– plan (n, v)",
    "– plane (n)",
    "– planet (n)",
    "– plant (n, v)",
    "– play (v, n)",
    "– please (v)",
    "– plural (ngôn ngữ học)",
    "– poem (n)",
    "– point (n, v)",
    "– poor (adj)",
    "– popular (adj)",
    "– populate (np)",
    "– port (n)",
    "– pose (v, n)",
    "– position (n)",
    "– possible (adj)",
    "– post (n, v)",
    "– pound (n)",
    "– power (n)",
    "– practice (n)",
    "– prepare (v)",
    "– present (adj, n, v)",
    "– press (n, v)",
    "– pretty (adv, adj)",
    "– print (v, n)",
    "– probable (adj)",
    "– problem (n)",
    "– process (n, v)",
    "– produce (v)",
    "– product (n)",
    "– proper (adj)",
    "– property (n)",
    "– protect (v)",
    "– prove (v)",
    "– provide (v)",
    "– pull (v, n)",
    "– push (v, n)",
    "– put (v)",
    "",
    "Q",
    "– quart",
    "– question (n, v)",
    "– quick (adj)",
    "– quiet (adj)",
    "– quite (adv)",
    "– quotient",
    "",
    "R",
    "– race (n, v)",
    "– radio (n)",
    "– rail (n)",
    "– rain (n, v)",
    "– raise (v)",
    "– ran (v)",
    "– range (n)",
    "– rather (adv)",
    "– reach (v)",
    "– read (v)",
    "– ready (adj)",
    "– real (adj)",
    "– reason (n)",
    "– receive (v)",
    "– record (n, v)",
    "– red (adj, n)",
    "– region (n)",
    "– remember (v)",
    "– repeat (v)",
    "– reply (n, v)",
    "– represent (v)",
    "– require (v)",
    "– rest (n, v)",
    "– result (n, v)",
    "– rich (adj)",
    "– ride (v, n)",
    "– right (adj, adv, n)",
    "– ring (n, v)",
    "– rise (n, v)",
    "– river (n)",
    "– road (n)",
    "– rock (n)",
    "– roll (n, v)",
    "– room (n)",
    "– root (n)",
    "– rope (n)",
    "– rose (n)",
    "– round (adj, adv, prep, n)",
    "– row (n)",
    "– rub (v)",
    "– rule (n, v)",
    "– run (v, n)",
    "",
    "S",
    "– safe (adj)",
    "– said (v)",
    "– sail (v, n)",
    "– salt (n)",
    "– same (adj, pron)",
    "– sand (n)",
    "– sat (v)",
    "– save (v)",
    "– saw (v)",
    "– say (v)",
    "– scale (n)",
    "– school (n)",
    "– science (n)",
    "– score (n, v)",
    "– sea (n)",
    "– search (n, v)",
    "– season (n)",
    "– seat (n)",
    "– second (det, adv, n)",
    "– section (n)",
    "– see (v)",
    "– seed (n)",
    "– seem",
    "– segment (n)",
    "– select (v)",
    "– self (n)",
    "– sell (v)",
    "– send (v)",
    "– sense (n)",
    "– sent (v)",
    "– sentence (n)",
    "– separate (adj, v)",
    "– serve (v)",
    "– set (n, v)",
    "– settle (v)",
    "– seven",
    "– several (det, pron)",
    "– shall (modal v)",
    "– shape (n, v)",
    "– share (v, n)",
    "– sharp (adj)",
    "– she (pron)",
    "– sheet (n)",
    "– shell (n)",
    "– shine (v)",
    "– ship (n)",
    "– shoe (n)",
    "– shop (n, v)",
    "– shore (n)",
    "– short (adj)",
    "– should (modal v)",
    "– shoulder (n)",
    "– shout (v, n)",
    "– show (v, n)",
    "– side (n)",
    "– sight (n)",
    "– sign (n, v)",
    "– silent (adj)",
    "– silver (n, adj)",
    "– similar (adj)",
    "– simple (adj)",
    "– since (prep, conj, adv)",
    "– sing (v)",
    "– single (adj)",
    "– sister (n)",
    "– sit (v)",
    "– six",
    "– size (n)",
    "– skill (n)",
    "– skin (n)",
    "– sky (n)",
    "– slave (n)",
    "– sleep (v, n)",
    "– slip (v)",
    "– slow (adj)",
    "– small (adj)",
    "– smell (v, n)",
    "– smile (v, n)",
    "– snow (n, v)",
    "– so (adv, conj)",
    "– soft (adj)",
    "– soil (n)",
    "– soldier (n)",
    "– solution (n)",
    "– solve (v)",
    "– some (det, pron)",
    "– son (n)",
    "– song (n)",
    "– soon (adv)",
    "– sound (n, v)",
    "– south (n, adj, adv)",
    "– space (n)",
    "– speak (v)",
    "– special (adj)",
    "– speech (n)",
    "– speed (n)",
    "– spell (v, n)",
    "– spend (v)",
    "– spoke (v)",
    "– spot (n)",
    "– spread (v)",
    "– spring (n)",
    "– square (adj, n)",
    "– stand (v, n)",
    "– star (n, v)",
    "– start  (v, n)",
    "– state (n, adj, v)",
    "– station (n)",
    "– stay (v, n)",
    "– stead (n)",
    "– steam (n)",
    "– steel (n)",
    "– step (n, v)",
    "– stick (v, n)",
    "– still (adv, adj)",
    "– stone (n)",
    "– stood (v)",
    "– stop (v, n)",
    "– store (n, v)",
    "– story (n)",
    "– straight (adv, adj)",
    "– strange (adj)",
    "– stream (n)",
    "– street (n)",
    "– stretch (v)",
    "– string (n)",
    "– strong (adj)",
    "– student (n)",
    "– study (n, v)",
    "– subject (n)",
    "– substance (n)",
    "– subtract (toán học)",
    "– success (n)",
    "– such  (det, pron)",
    "– sudden (adj)",
    "– suffix (ngôn ngữ học)",
    "– sugar (n)",
    "– suggest (v)",
    "– suit (n, v)",
    "– summer (n)",
    "– sun (n)",
    "– supply (n, v)",
    "– support (n, v)",
    "– sure (adj, adv)",
    "– surface (n)",
    "– surprise (n, v)",
    "– swim (v)",
    "– syllable (n)",
    "– symbol (n)",
    "– system (n)",
    "",
    "T",
    "– table (n)",
    "– tail (n)",
    "– take (v)",
    "– talk (v, n)",
    "– tall (adj)",
    "– teach (v)",
    "– team (n)",
    "– teeth",
    "– tell (v)",
    "– temperature (n)",
    "– ten",
    "– term (n)",
    "– test (n, v)",
    "– than (prep, conj)",
    "– thank (v)",
    "– that (det, pron, conj)",
    "– the (art)",
    "– their (det)",
    "– them (pron)",
    "– then (adv)",
    "– there (adv)",
    "– these",
    "– they (pron)",
    "– thick (adj)",
    "– thin (adj)",
    "– thing (n)",
    "– think (v)",
    "– third",
    "– this (det, pron)",
    "– those",
    "– though (conj, adv)",
    "– thought (n)",
    "– thousand",
    "– three",
    "– through (prep, adv)",
    "– throw (v)",
    "– thus (adv)",
    "– tie (v, n)",
    "– time (n)",
    "– tiny (adj)",
    "– tire (v)",
    "– to (prep)",
    "– together (adv)",
    "– told (v)",
    "– tone (n)",
    "– too (adv)",
    "– took (n)",
    "– tool (n)",
    "– top (n, adj)",
    "– total (adj, n)",
    "– touch (v, n)",
    "– toward (từ cổ,nghĩa cổ)",
    "– town (n)",
    "– track (n)",
    "– trade (n, v)",
    "– train (n, v)",
    "– travel (v)",
    "– tree (n)",
    "– triangle (n)",
    "– trip (n, v)",
    "– trouble (n)",
    "– truck (n)",
    "– true (adj)",
    "– try (v)",
    "– tube (n)",
    "– turn (v, n)",
    "– twenty",
    "– two",
    "– type (n, v)",
    "",
    "U",
    "– under (prep, adv)",
    "– unit (n)",
    "– until (conj, prep)",
    "– up (adv, prep)",
    "– us (pron)",
    "– use (v, n)",
    "– usual (adj)",
    "",
    "V",
    "– valley (n)",
    "– value (n, v)",
    "– vary (v)",
    "– verb (ngôn ngữ học)",
    "– very (adv)",
    "– view (n, v)",
    "– village (n)",
    "– visit (v, n)",
    "– voice (n)",
    "– vowel (ngôn ngữ học)",
    "",
    "W",
    "– wait (v)",
    "– walk (v, n)",
    "– wall (n)",
    "– want (v)",
    "– war (n)",
    "– warm (adj, v)",
    "– was",
    "– wash (v)",
    "– watch (v, n)",
    "– water (n)",
    "– wave (n)",
    "– way (n)",
    "– we (pron)",
    "– wear (v)",
    "– weather (n)",
    "– week (n)",
    "– weight (n)",
    "– well (adv, adj)",
    "– went (v)",
    "– were",
    "– west (n, adj, adv)",
    "– what (pron, det)",
    "– wheel (n)",
    "– when (adv, pron, conj)",
    "– where (adv, conj)",
    "– whether (conj)",
    "– which  (pron, det)",
    "– while (conj, n)",
    "– white (adj, n)",
    "– who (pron)",
    "– whole (adj, n)",
    "– whose (det, pron)",
    "– why (adv)",
    "– wide (adj)",
    "– wife (n)",
    "– wild  (adj)",
    "– will (modal v, n)",
    "– win (v)",
    "– wind (n)",
    "– window (n)",
    "– wing (n)",
    "– winter (n)",
    "– wire (n)",
    "– wish (v, n)",
    "– with (prep)",
    "– woman (n)",
    "– women (n)",
    "– wonder (v)",
    "– won’t (n)",
    "– wood (n)",
    "– word (n)",
    "– work (v, n)",
    "– world (n)",
    "– would (n)",
    "– write (v)",
    "– written (adj)",
    "– wrong (adj, adv)",
    "– wrote (v)",
    "",
    "Y",
    "– yard (n)",
    "– year (n)",
    "– yellow (adj)",
    "– yes",
    "– yet (adv)",
    "– you (pron)",
    "– young (adj)",
    "– your (det)"
];

let vData = [
    "Dịch nghĩa",
    "A",
    "có năng lực, có tài",
    "bỏ, từ bỏ",
    "khoảng, về",
    "ở trên, lên trên",
    "hành động, hành vi, cử chỉ, đối xử",
    "cộng, thêm vào",
    "sợ, sợ hãi, hoảng sợ",
    "sau, đằng sau, sau khi",
    "lại, nữa, lần nữa",
    "chống lại, phản đối",
    "tuổi",
    "trước đây",
    "đồng ý, tán thành",
    "không khí, bầu không khí, không gian",
    "tất cả",
    "cho phép, để cho",
    "cũng, cũng vậy, cũng thế",
    "luôn luôn",
    "giữa, ở giữa",
    "(từ cổ,nghĩa cổ); (thông tục); (tiếng địa phương) nếu",
    "và",
    "sự tức giận, sự giận dữ",
    "động vật, thú vật",
    "sự trả lời; trả lời",
    "một người, vật nào đó; bất cứ; một chút nào, tí nào",
    "xuất hiện, hiện ra, trình diện",
    "quả táo",
    "chúng tôi",
    "diện tích, bề mặt",
    "cánh tay; vũ trang, trang bị (vũ khí)",
    "sắp xếp, sắp đặt, sửa soạn",
    "đến, tới nơi",
    "nghệ thuật, mỹ thuật",
    "như (as you know…)",
    "hỏi",
    "ở tại (chỉ vị trí)",
    "nguyên tử",
    "",
    "B",
    "đứa bé mới sinh; trẻ thơ",
    "lưng, về phía sau, trở lại",
    "xấu, tồi",
    "quả bóng",
    "băng, đai, nẹp",
    "bờ (sông…), đê",
    "quán bán rượu",
    "cơ sở, cơ bản, nền móng; đặt tên, đặt cơ sở trên cái gì",
    "cơ bản, cơ sở",
    "(thể dục,thể thao) gây (đánh bóng chày, crikê); (từ cổ,nghĩa cổ) vợt (quần vợt)",
    "thì, là",
    "mang, cầm, vác, đeo, ôm",
    "tiếng đập, sự đập; đánh đập, đấm",
    "vẻ đẹp, cái đẹp; người đẹp",
    "cái giường",
    "thì, là",
    "trước, đằng trước",
    "bắt đầu, mở đầu, khởi đầu",
    "bắt đầu, khởi đầu",
    "sau, ở đằng sau",
    "tin, tin tưởng",
    "cái chuông, tiếng chuông",
    "tốt nhất",
    "tốt hơn",
    "giữa, ở giữa",
    "to, lớn",
    "Con chim",
    "miếng, mảnh",
    "đen; màu đen",
    "khối, tảng (đá); làm ngăn cản, ngăn chặn",
    "máu, huyết; sự tàn sát, chem giết",
    "nở hoa; sự nở hoa",
    "xanh, màu xanh",
    "tấm ván; lát ván, lót ván",
    "tàu, thuyền",
    "thân thể, thân xác",
    "xương",
    "sách; ghi chép",
    "sinh, đẻ",
    "cả hai",
    "phần dưới cùng, thấp nhất; cuối, cuối cùng",
    "mua",
    "hộp, thùng",
    "con trai, thiếu niên",
    "ngành; nhành cây, nhánh song, ngả đường",
    "bánh mỳ",
    "bẻ gãy, đập vỡ; sự gãy, sự vỡ",
    "sáng, sáng chói",
    "mang, cầm, xách lại",
    "rộng",
    "khánh kiệt, túng quẫn, bần cùng",
    "anh, em trai",
    "cầm lại, đem lại, mang lại, xách lại, đưa lại",
    "nâu, màu nâu",
    "xây dựng",
    "đốt, đốt cháy, thắp, nung, thiêu",
    "bận, bận rộn",
    "nhưng",
    "mua",
    "bởi, bằng",
    "",
    "C",
    "gọi; tiếng kêu, tiếng gọi",
    "khung chì (để) lắp kinh (cửa)",
    "trại, chỗ cắm trại; cắm trại, hạ trại",
    "có thể; nhà tù, nhà giam, bình, ca đựng",
    "thủ đô, tiền vốn; chủ yếu, chính yếu, cơ bản",
    "người cầm đầu, người chỉ huy, thủ lĩnh",
    "xe hơi",
    "thẻ, thiếp",
    "sự chăm sóc, chăm nom; chăm sóc",
    "mang, vác, khuân chở",
    "vỏ, ngăn, túi",
    "con mèo",
    "bắt lấy, nắm lấy, tóm lấy, chộp lấy",
    "sự bắt, sự nắm lấy; cái bắt, cái vồ, cái chộp",
    "nguyên nhân, nguyên do; gây ra, gây nên",
    "ô, ngăn",
    "đồng xu (=1/100 đô la)",
    "(như) centre",
    "thế kỷ",
    "chắc chắn",
    "ghế",
    "sự may mắn",
    "thay đổi, sự thay đổi, sự biến đổi",
    "tính cách, đặc tính, nhân vật",
    "nhiệm vụ, bổn phận, trách nhiệm; giao nhiệm vụ, giao việc",
    "đồ thị, biểu đồ; vẽ đồ thị, lập biểu đồ",
    "kiểm tra; sự kiểm tra",
    "gà con; chim con",
    "trọng yếu, chính yếu; thủ lĩnh, lãnh tụ, người đứng đầu, xếp",
    "đứa bé, đứa trẻ",
    "đứa bé, đứa trẻ",
    "chọn, lựa chọn",
    "(thơ ca) dây (đàn hạc)",
    "đường tròn, hình tròn",
    "thành phố",
    "đòi hỏi, yêu sách; sự đòi hỏi, sự yêu sách, sự thỉnh cầu",
    "lớp học",
    "sạch, sạch sẽ",
    "lau chùi, quét dọn",
    "leo, trèo",
    "đồng hồ",
    "đóng kín, chật chội, che đậy, đóng, khép, kết thúc, chấm dứt",
    "mặc quần áo cho",
    "mây, đám mây",
    "sự lao dốc; bờ biển",
    "áo choàng",
    "lạnh, sự lạnh lẽo, lạnh nhạt",
    "sưu tập, tập trung lại",
    "thuộc địa",
    "(như) colour",
    "cột, mục (báo)",
    "đến, tới, đi đến, đi tới",
    "công, công cộng, thông thường, phổ biến",
    "công ty",
    "so sánh, đối chiếu",
    "hoàn thành, xong",
    "điều kiện, tình cảnh, tình thế",
    "kết nối, nối",
    "cân nhắc, xem xét; để ý, quan tâm, lưu ý đến",
    "(âm nhạc) thuận tai, êm ái, du dương",
    "bao hàm, chứa đựng, bao gồm",
    "lục địa, đại lục (lục địa Bắc Mỹ)",
    "tiếp tục, làm tiếp",
    "sự điều khiển, quyền hành, quyền lực, quyền chỉ huy",
    "nấu ăn, người nấu ăn",
    "mát mẻ, điềm tĩnh; làm mát",
    "bản sao, bản chép lại; sự sao chép; sao chép, bắt chước",
    "hai (chân)",
    "góc (tường, nhà, phố…)",
    "đúng, chính xác; sửa, sửa chữa",
    "giá, chi phí; trả giá, phải trả",
    "bông, chỉ, sợi",
    "có thể, có khả năng",
    "đếm, tính",
    "nước, quốc gia, đất nước",
    "tiến trình, quá trình diễn tiến; sân chạy đua",
    "bao bọc, che phủ; vỏ, vỏ bọc",
    "con bò cái",
    "nếp nhăn, nếp gấp",
    "sáng tạo, tạo nên",
    "vụ mùa",
    "cây Thánh Giá, nỗi thống khổ; sự băng qua; băng qua, vượt qua",
    "đám đông",
    "khóc, kêu la; sự khóc, tiếng khóc, sự kêu la",
    "hiện hành, phổ biến, hiện nay; dòng (nước), luống (gió)",
    "cắt, chặt; sự cắt",
    "",
    "D",
    "bố, cha",
    "sự nhảy múa, sự khiêu vũ; nhảy múa, khiêu vũ",
    "sự nguy hiểm, mối hiểm nghèo; nguy cơ, mối đe dọa",
    "tối, tối tăm; bóng tối, ám muội",
    "ngày, ban ngày",
    "chết, tắt",
    "phân phát, phân phối; sự giao dịch, thỏa thuận mua bán",
    "thân, thân yêu, thân mến; kính thưa, thưa",
    "sự chết, cái chết",
    "quyết định, giải quyết, phân xử",
    "(toán học) thập phân",
    "sâu, khó lường, bí ẩn",
    "mức độ, trình độ; bằng cấp; độ",
    "phụ thuộc, tuỳ thuộc, tuỳ thuộc",
    "diễn tả, miêu tả, mô tả",
    "sa mạc; công lao, giá trị; rời bỏ, bỏ trốn",
    "sự thiết kế, kế hoạch, đề cương. phác thảo; phác họa, thiết kế",
    "xác định, định rõ; quyết định",
    "phát triển, mở rộng; trình bày, bày tỏ",
    "từ điển",
    "chết, từ trần, hy sinh",
    "khác, không giống",
    "khó, khó khăn, gay go",
    "trực tiếp, thẳng, thẳng thắn; gửi, viết cho ai, điều khiển",
    "thảo luận, tranh luận",
    "xa, cách, xa cách",
    "chia, chia ra, phân ra",
    "sự chia, sự phân chia, sự phân loại",
    "làm, làm",
    "Dr)) bác sĩ y khoa, tiến sĩ",
    "hươu cái, hoãng cái; nai cái",
    "chó",
    "đô la Mỹ",
    "xong, hoàn thành, đã thực hiện",
    "cửa, cửa ra vào",
    "đôi, hai, kép; cái gấp đôi, lượng gấp đôi; làm gấp đôi",
    "xuống",
    "vẽ, kéo",
    "giấc mơ, mơ",
    "Váy liền thân",
    "đồ uống; uống",
    "lái, đua xe; cuộc đua xe (điều khiển",
    "chảy nhỏ giọt, rơi, rớt; giọt (nước, máu…);",
    "khô, cạn; làm khô, sấy khô",
    "con vịt, vịt cái",
    "trong lúc, trong thời gian",
    "E",
    "mỗi",
    "tai",
    "sớm",
    "đất, trái đất",
    "sự thanh thản, sự thoải mái; làm thanh thản, làm yên tâm, làm dễ chịu",
    "hướng đông, phía đông, (thuộc) đông, ở phía đông",
    "ăn",
    "lưỡi, cạnh sắc",
    "hiệu ứng, hiệu quả, kết quả",
    "trứng",
    "tám",
    "mỗi, một; cũng phải thế",
    "(thuộc) điện, có điện, phát điện",
    "yếu tố, nguyên tố",
    "khác, nữa; nếu không",
    "giới hạn, sự kết thúc; kết thúc, chấm dứt",
    "kẻ thù, quân địch",
    "năng lượng, nghị lực, sinh lực",
    "máy, động cơ",
    "đủ",
    "đi vào, gia nhập",
    "ngang, bằng; người ngang hàng, ngang tài, sức; bằng, ngang",
    "làm cân bằng, san bằng",
    "đặc biệt là, nhất là",
    "ngay cả, ngay, lại còn; bằng phẳng, điềm đạm, ngang bằng",
    "buổi chiều, tối",
    "sự việc, sự kiện",
    "từng, từ trước tới giờ",
    "mỗi, mọi",
    "chính xác, đúng",
    "thí dụ, ví dụ",
    "trừ ra, không kể; trừ phi",
    "kích thích, kích động",
    "bài tập, sự thi hành, sự thực hiện; làm, thi hành, thực hiện",
    "chờ đợi, mong ngóng; liệu trước",
    "kinh nghiệm; trải qua, nếm mùi",
    "cuộc thí nghiệm; thí nghiệm",
    "mắt",
    "",
    "F",
    "mặt, thể diện; đương đầu, đối phó, đối mặt",
    "việc, sự việc, sự kiện",
    "hợp lý, công bằng; thuận lợi",
    "rơi, ngã, sự rơi, ngã",
    "gia đình, thuộc gia đình",
    "nổi tiếng",
    "xa",
    "trang trại",
    "nhanh",
    "béo, béo bở; mỡ, chất béo",
    "cha (bố)",
    "thiện ý; sự quý mến",
    "sự sợ hãi, e sợ; sợ, lo ngại",
    "cho ăn, nuôi",
    "cảm thấy",
    "chân, bàn chân (người, thú…)",
    "da lông (của thú vật)",
    "nỉ, phớt",
    "ít, vài; một ít, một vài",
    "cánh đồng, bãi chiến trường",
    "(thực vật học) quả sung; quả vả",
    "đấu tranh, chiến đấu; sự đấu tranh, cuộc chiến đấu",
    "hình dáng, nhân vật; hình dung, miêu tả",
    "làm đấy, lấp kín",
    "cuối cùng, cuộc đấu chung kết",
    "tìm, tìm thấy",
    "tốt, giỏi",
    "ngón tay",
    "kết thúc, hoàn thành; sự kết thúc, phần cuối",
    "lửa; đốt cháy",
    "thứ nhất, đầu tiên, trước hết; người, vật đầu tiên, thứ nhất",
    "cá, món cá; câu cá, bắt cá",
    "hợp, vừa; thích hợp, xứng đáng",
    "năm",
    "bằng phẳng, bẹt, nhẵn; dãy phòng, căn phòng, mặt phẳng",
    "sàn, tầng (nhà)",
    "sự chảy; chảy",
    "hoa, bông, đóa, cây hoa",
    "bay; sự bay, quãng đường bay",
    "đi theo sau, theo, tiếp theo",
    "đồ ăn, thức, món ăn",
    "chân, bàn chân",
    "cho, dành cho…",
    "sức mạnh; ép buộc, cưỡng ép",
    "rừng",
    "hình thể, hình dạng, hình thức; làm thành, được tạo thành",
    "về tương lai, sau này ở phía trước, tiến về phía trước; ở phía trước, tiến về phía trước",
    "(q.k of find) tìm, tìm thấy",
    "bốn",
    "(toán học) phân số",
    "miễn phí, tự do, giải phóng, trả tự do",
    "tươi, tươi tắn",
    "người bạn",
    "từ",
    "mặt; đằng trước, về phía trước",
    "quả, trái cây",
    "đầy, đầy đủ",
    "sự vui đùa, sự vui thích; hài hước",
    "",
    "G",
    "trò chơi",
    "vườn",
    "khí, hơi đốt",
    "tập hợp; hái, lượm, thu thập",
    "cho, biếu, tặng, ban",
    "chung, chung chung; tổng",
    "hiền lành, dịu dàng, nhẹ nhàng",
    "được, có được",
    "con gái",
    "cho, biếu, tặng",
    "vui lòng, sung sướng",
    "kính, thủy tinh, cái cốc, ly",
    "đi",
    "vàng; bằng vàng",
    "đã đi, đã đi khỏi; đã trôi qua, đã qua",
    "tốt, hay, tuyệt; điều tốt, điều thiện",
    "có",
    "cầm quyền, cai trị",
    "rộng lớn, vĩ đại",
    "cỏ; bãi cỏ, đồng cỏ",
    "xám, hoa râm (tóc)",
    "to, lớn, vĩ đại",
    "xanh lá cây",
    "mọc, mọc lên (cây cối); mọc mầm, đâm chồi nẩy nở",
    "mặt đất, đất, bãi đất",
    "nhóm",
    "mọc, mọc lên",
    "đoán, phỏng đoán; sự đoán, sự ước chừng",
    "điều chỉ dẫn, người hướng dẫn; dẫn đường, chỉ đường",
    "súng",
    "",
    "H",
    "có",
    "tóc",
    "một nửa, phần chia đôi, nửa giờ; nửa",
    "tay, bàn tay; trao tay, truyền cho",
    "xảy ra, xảy đến",
    "vui sướng, hạnh phúc",
    "cứng, rắn, hà khắc; hết sức cố gắng, tích cực",
    "có",
    "cái mũ",
    "có",
    "nó, anh ấy, ông ấy",
    "cái đầu (người thú); chỉ huy, lãnh đại, dẫn đầu",
    "nghe",
    "nghe",
    "tim, trái tim",
    "hơi nóng, sức nóng",
    "nặng, nặng nề",
    "khoang (của tàu thuỷ)",
    "giúp đỡ; sự giúp đỡ",
    "nó, chị ấy, cô ấy, bà ấy",
    "đây, ở đây",
    "cao, ở mức độ cao",
    "đồi",
    "nó, hắn, ông ấy, anh ấy",
    "của nó, của hắn, của ông ấy, của anh ấy; cái của nó, cái của hắn, cái của ông ấy, cái của anh ấy",
    "lịch sử, sử học",
    "đánh, đấm, ném trúng; đòn, cú đấm",
    "cầm, nắm, giữ; sự cầm, sự nắm giữ",
    "lỗ, lỗ trống; hang",
    "nhà; ở tại nhà, nước mình",
    "hy vọng; nguồn hy vọng",
    "ngựa",
    "nóng, nóng bức",
    "giờ",
    "nhà, căn nhà, toàn nhà",
    "thế nào, như thế nào, làm sao, ra sao",
    "to lớn, khổng lồ",
    "(thuộc) con người, loài người",
    "trăm",
    "săn, đi săn",
    "sự vội vàng, sự gấp rút",
    "",
    "I",
    "một (chữ số La mã); tôi",
    "băng, nước đá",
    "ý tưởng, quan niệm",
    "nếu, nếu như",
    "tưởng tượng, hình dung; tưởng rằng, cho rằng",
    "ở, tại, trong; vào",
    "insơ (đơn vị đo chiều dài Anh bằng 2, 54 cm)",
    "bao gồm, tính cả",
    "chỉ, cho biết; biểu thị, trình bày ngắn gọn",
    "công nghiệp, kỹ nghệ",
    "sâu bọ, côn trùng",
    "lúc, chốc lát",
    "dụng cụ âm nhạc khí",
    "sự thích thú, sự quan tâm, chú ý; làm quan tâm, làm chú ý",
    "phát minh, sáng chế",
    "sắt; bọc sắt",
    "là",
    "hòn đảo",
    "cái đó, điều đó, con vật đó",
    "",
    "J",
    "việc, việc làm",
    "gia nhập, tham gia; nối, chắp, ghép",
    "niềm vui, sự vui mừng",
    "nhảy; sự nhảy, bước nhảy",
    "đúng, vừa đủ; vừa mới, chỉ",
    "",
    "K",
    "giữ, giữ lại",
    "giữ, giữ lại",
    "chìa khóa, khóa, thuộc (khóa)",
    "giết, tiêu diệt",
    "loại, giống; tử tế, có lòng tốt",
    "vua, quốc vương",
    "biết; hiểu biết",
    "biết",
    "",
    "L",
    "người yêu, vợ, quý bà, tiểu thư",
    "hồ",
    "đất, đất canh tác, đất đai",
    "ngôn ngữ",
    "rộng, lớn, to",
    "lầm cuối, sau cùng; người cuối cùng; cuối cùng, rốt hết; kéo dài",
    "trễ, muộn",
    "cười; tiếng cười",
    "luật",
    "xếp, đặt, bố trí",
    "lãnh đạo, dẫn dắt; sự lãnh đạo, sự hướng dẫn",
    "học, nghiên cứu",
    "tối thiểu; ít nhất",
    "bỏ đi, rời đi, để lại",
    "lãnh đạo, dẫn dắt; sự lãnh đạo, sự hướng dẫn",
    "bên trái; về phía trái",
    "chân (người, thú, bàn…)",
    "chiều dài, độ dài",
    "nhỏ bé, ít hơn; số lượng ít hơn",
    "cho phép, để cho",
    "thư; chữ cái, mẫu tự",
    "trình độ, cấp, vị trí; bằng, ngang bằng",
    "nói dối; lời nói dối, sự dối trá",
    "đời, sự sống",
    "giơ lên, nhấc lên; sự nâng, sự nhấc lên",
    "ánh sáng; nhẹ, nhẹ nhàng; đốt, thắp sáng",
    "giống như; thích; như",
    "dây, đường, tuyến",
    "chất lỏng; lỏng, êm ái, du dương, không vững",
    "danh sách; ghi vào danh sách",
    "nghe, lắng nghe",
    "nhỏ, bé, chút ít; không nhiều; một chút",
    "sống",
    "xác định vị trí, định vị",
    "khúc gỗ mới đốn, khúc gỗ mới xẻ",
    "(thơ ca) hiu quạnh",
    "dài, xa; lâu",
    "nhìn; cái nhìn",
    "thua, mất",
    "thăm, việc rút thăm; sự chọn bằng cách rút thăm",
    "to, inh ỏi, ầm ĩ; to, lớn (nói)",
    "Yêu",
    "thấp, bé, lùn",
    "",
    "M",
    "máy, máy móc",
    "làm, hoàn thành, thực hiện",
    "nam châm",
    "chính, chủ yếu, trọng yếu nhất",
    "lớn, nhiều hơn, trọng đại, chủ yếu",
    "làm, chế tạo; sự chế tạo",
    "con người; đàn ông",
    "nhiều",
    "bản đồ",
    "dấu, nhãn, nhãn mác; đánh dấu, ghi dấu",
    "chợ, thị trường;",
    "khối, khối lượng; quần chúng, đại chúng",
    "chủ, chủ nhân, thầy giáo, thạc sĩ",
    "trận thi đấu, đối thủ, địch thủ; đối chọi, sánh được",
    "nguyên vật liệu; vật chất, hữu hình",
    "chất, vật chất; có ý nghĩa, có tính chất quan trọng",
    "tháng 5",
    "tôi, tao, tớ",
    "nghĩa, có nghĩa là",
    "khoảng giữa, trung độ, trung gian, trung dung",
    "đo, đo lường; sự đo lường, đơn vị đo lường;",
    "thịt",
    "gặp, gặp gỡ",
    "giai điệu",
    "Những người đàn ông",
    "kim loại",
    "phương pháp, cách thức",
    "giữa, ở giữa",
    "có thể, có lẽ",
    "dặm (đo lường)",
    "sữa",
    "triệu",
    "tâm trí, tinh thần, trí tuệ; chú ý, để ý, chăm sóc, quan tâm",
    "của tôi",
    "phút",
    "cô gái, thiếu nữ",
    "pha, trộn lẫn; sự pha trộn",
    "hiện đại, tân tiến",
    "(hoá học) phân tử",
    "chốc, lát",
    "tiền",
    "tháng",
    "mặt trăng",
    "hơn, nhiều hơn",
    "buổi sáng",
    "lớn nhất, nhiều nhất; nhất, hơn cả",
    "mẹ",
    "sự chuyển động, sụ di động",
    "leo, trèo; núi",
    "núi",
    "miệng",
    "di chuyển, chuyển động; sự di chuyển, sự chuyển động",
    "nhiều, lắm",
    "nhân lên, làm tăng lên nhiều lần; sinh sôi nảy nở",
    "nhạc, âm nhạc",
    "phải, cần, nên làm",
    "của tôi",
    "",
    "N",
    "tên; đặt tên, gọi tên",
    "dân tộc, quốc gia",
    "(thuộc) tự nhiên, thiên nhiên",
    "tự nhiên, thiên nhiên",
    "gần, cận; ở gần",
    "cần, cần thiết, thiết yếu",
    "cổ",
    "cần, đòi hỏi; sự cần",
    "Hàng xóm",
    "không bao giờ, không khi nào",
    "mới, mới mẻ, mới lạ",
    "sát, gần, bên cạnh; lần sau, tiếp nữa",
    "đêm, tối",
    "chín",
    "không",
    "tiếng ồn, sự huyên náo",
    "trưa, buổi trưa",
    "cũng không",
    "phía bắc, phương bắc",
    "mũi",
    "lời ghi, lời ghi chép; ghi chú, ghi chép",
    "không gì, không cái gì",
    "thông báo, yết thị; chú ý, để ý, nhận biết",
    "danh từ",
    "bây giờ, hiện giờ, hiện nay",
    "số",
    "số",
    "",
    "O",
    "vật, vật thể; phản đối, chống lại",
    "quan sát, theo dõi",
    "xảy ra, xảy đến, xuất hiện",
    "đại dương",
    "của",
    "tắt; khỏi, cách, rời",
    "biếu, tặng, cho; sự trả giá",
    "cơ quan, văn phòng, bộ",
    "thường, hay, luôn",
    "chao, ôi chao, chà, này..",
    "dầu",
    "già",
    "trên, ở trên; tiếp tục, tiếp diễn",
    "một lần; khi mà, ngay khi, một khi",
    "một; một người, một vật nào đó",
    "chỉ có 1, duy nhất; chỉ, mới",
    "mở, ngỏ; mở, bắt đầu, khai mạc",
    "hoạt động, điều khiển",
    "đối nhau, ngược nhau; trước mặt, đối diện; điều trái ngược",
    "vàng (ở huy hiệu)",
    "thứ, bậc; ra lệnh",
    "đàn óoc gan",
    "(thuộc) gốc, nguồn gốc, căn nguyên; nguyên bản",
    "khác",
    "của chúng ta, thuộc chúng ta, của chúng tôi, của chúng mình",
    "ngoài, ở ngoài, ra ngoài",
    "bên trên, vượt qua; lên, lên trên",
    "của chính mình, tự mình; nhận, nhìn nhận",
    "Oxy",
    "",
    "P",
    "trang (sách)",
    "sơn, vôi màu; sơn, quét sơn",
    "đôi, cặp",
    "giấy",
    "đoạn văn",
    "cha, mẹ",
    "phần, bộ phận",
    "riêng biệt, cá biệt",
    "tiệc, buổi liên hoan; đảng",
    "qua, vượt qua, ngang qua",
    "quá khứ, dĩ vãng; quá, qua",
    "đường mòn; hướng đi",
    "mẫu, khuôn mẫu",
    "trả, thanh toán, nộp; tiền lương",
    "dân tộc, dòng giống; người",
    "có thể, có lẽ",
    "kỳ, thời kỳ, thời gian; thời đại",
    "con người, người",
    "câu; thành ngữ, cụm từ",
    "cuốc (đất); đào, khoét (lỗ)",
    "bức vẽ, bức họa",
    "mảnh, mẩu; đồng tiền",
    "sân (chơi các môn thể thao); đầu hắc ín",
    "nơi, địa điểm; quảng trường",
    "ngay thẳng, đơn giản, chất phác",
    "bản đồ, kế hoạch; vẽ bản đồ, lập kế hoạch, dự kiến",
    "mặt phẳng, mặt bằng",
    "hành tinh",
    "thực vật, sự mọc lên; trồng, gieo",
    "chơi, đánh; sự vui chơi, trò chơi, trận đấu",
    "làm vui lòng, vừa lòng, mong… vui lòng, xin mời",
    "ở số nhiều, (thuộc) số nhiều",
    "bài thơ",
    "point mũi nhọn, điểm; vót, làm nhọn, chấm (câu..)",
    "nghèo",
    "có tính đại chúng, (thuộc) nhân dân; được nhiều người ưa chuộng",
    "ở, cư trú (một vùng)",
    "cảng",
    "đưa ra, đề ra, đặt; sự đặt, đề ra",
    "vị trí, chỗ",
    "có thể, có thể thực hiện",
    "thư, bưu kiện; gửi thư",
    "pao – đơn vị đo lường",
    "khả năng, tài năng, năng lực; sức mạnh, nội lực; quyền lực",
    "thực hành, thực tiễn",
    "sửa soạn, chuẩn bị",
    "có mặt, hiện diện; hiện nay, hiện thời; bày tỏ, giới thiệu, trình bày",
    "sự ép, sự nén, sự ấn; ép, nén, bóp, ấn",
    "khá, vừa phải; xinh, xinh xắn; đẹp",
    "in, xuất bản; sự in ra",
    "có thể, có khả năng",
    "vấn đề, điều khó giải quyết",
    "quá trình, sự tiến triển, quy trình; chế biến, gia công, xử lý",
    "sản xuất, chế tạo",
    "sản phẩm",
    "đúng, thích đáng, thích hợp",
    "tài sản, của cải; đất đai, nhà cửa, bất động sản",
    "bảo vệ, che chở",
    "chứng tỏ, chứng minh",
    "chuẩn bị đầy đủ, dự phòng; cung cấp, chu cấp",
    "lôi, kéo, giật; sự lôi kéo, sự giật",
    "xô đẩy; sự xô đẩy",
    "đặt, để, cho vào",
    "",
    "Q",
    "góc tư galông, lít Anh (bằng 1, 135 lít)",
    "câu hỏi; hỏi, chất vấn",
    "nhanh",
    "lặng, yên lặng, yên tĩnh",
    "hoàn toàn, hầu hết",
    "(toán học) số thương",
    "",
    "R",
    "loài, chủng, giống; cuộc đua; đua",
    "sóng vô tuyến, radio",
    "đường ray",
    "mưa, cơn mưa; mưa",
    "nâng lên, đưa lên, ngẩng lên",
    "Chạy",
    "dãy, hàng, loại; phạm vi, trình độ",
    "thà.. còn hơn, thích… hơn",
    "đến, đi đến, tới",
    "đọc",
    "sẵn sàng",
    "thực, thực tế, có thật",
    "lý do, lý lẽ",
    "nhận, lĩnh, thu",
    "bản ghi, sự ghi, bản thu, sự thu; thu, ghi chép",
    "đỏ; màu đỏ",
    "vùng, miền",
    "nhớ, nhớ lại",
    "nhắc lại, lặp lại",
    "sự trả lời, sự hồi âm; trả lời, hồi âm",
    "miêu tả, hình dung; đại diện, thay mặt",
    "đòi hỏi, yêu cầu, quy định",
    "sự nghỉ ngơi, lúc nghỉ; nghỉ, nghỉ ngơi",
    "kết quả; bởi, do.. mà ra, kết quả là…",
    "giàu, giàu có",
    "đi, cưỡi (ngựa); sự đi, đường đi",
    "thẳng, phải, tốt; ngay, đúng; điều thiện, điều phải, tốt, bên phải",
    "chiếc nhẫn, đeo nhẫn cho ai",
    "sự lên, sự tăng lương, thăng cấp; dậy, đứng lên, mọc (mặt trời), thành đạt",
    "sông",
    "con đường, đường phố",
    "đá",
    "cuốn, cuộn, sự lăn tròn; lăn, cuốn, quấn, cuộn",
    "phòng, buồng",
    "gốc, rễ",
    "dây cáp, dây thừng, xâu, chuỗi",
    "hoa hồng; cây hoa hồng",
    "tròn, vòng quanh, xung quanh",
    "hàng, dây",
    "cọ xát, xoa bóp, nghiền, tán",
    "quy tắc, điều lệ, luật lệ; cai trị, chỉ huy, điều khiển",
    "chạy; sự chạy",
    "",
    "S",
    "an toàn, chắc chắn, đáng tin",
    "nói",
    "đi tàu, thuyền, nhổ neo; buồm, cánh buồm, chuyến đi bằng thuyền buồm",
    "muối",
    "đều đều, đơn điệu; cũng như thế, vẫn cái đó",
    "cát",
    "ngồi",
    "cứu, lưu",
    "nhìn",
    "nói",
    "vảy (cá..)",
    "Trường học",
    "khoa học, khoa học tự nhiên",
    "điểm số, bản thắng, tỷ số; đạt được, thành công, cho điểm",
    "biển",
    "sự tìm kiếm, sự thăm dò, sự điều tra; tìm kiếm, thăm dò, điều tra",
    "mùa",
    "ghế, chỗ ngồi",
    "thứ hai, ở vị trí thứ 2, thứ nhì; người về nhì",
    "mục, phần",
    "nhìn, nhìn thấy, quan sát",
    "hạt, hạt giống",
    "có vẻ như, dường như, coi bộ",
    "đoạn, khúc, đốt, miếng;",
    "chọn lựa, chọn lọc",
    "bản thân mình",
    "bán",
    "gửi, phái đi",
    "giác quan, tri giác, cảm giác",
    "gửi, sai, phái, cho đi ((cũng) scend)",
    "câu",
    "khác nhau, riêng biệt; làm rời, tách ra, chia tay",
    "phục vụ, phụng sự",
    "bộ, bọn, đám, lũ; đặt để, bố trí",
    "giải quyết, dàn xếp, hòa giải, đặt, bố trí",
    "bảy",
    "vài",
    "dự đoán tương lai: sẽ",
    "hình, hình dạng, hình thù",
    "đóng góp, tham gia, chia sẻ; phần đóng góp, phần tham gia, phần chia sẻ",
    "sắc, nhọn, bén",
    "nó, bà ấy, chị ấy, cô ấy…",
    "chăn, khăn trải giường; lá, tấm, phiến, tờ",
    "vỏ, mai; vẻ bề ngoài",
    "chiếu sáng, tỏa sáng",
    "tàu, tàu thủy",
    "giày",
    "cửa hàng; đi mua hầng, đi chợ",
    "bờ (biển, hồ lớn), bờ biển",
    "ngắn, cụt",
    "nên",
    "vai",
    "hò hét, reo hò; sự la hét, sự hò reo",
    "biểu diễn, trưng bày; sự biểu diễn, sự bày tỏ",
    "mặt, mặt phẳng",
    "cảnh đẹp; sự nhìn",
    "dấu, dấu hiệu, kí hiệu đánh dấu, viết ký hiệu",
    "im lặng, yên tĩnh",
    "bạc, đồng bạc; làm bằng bạc, trắng như bạc",
    "giống như, tương tự như",
    "đơn, đơn giản, dễ dàng",
    "từ, từ khi; từ khi, từ lúc đó; từ đó, từ lúc ấy",
    "hát, ca hát",
    "đơn, đơn độc, đơn lẻ",
    "chị, em gái",
    "ngồi",
    "sáu",
    "cỡ",
    "kỹ năng, kỹ sảo",
    "da, vỏ",
    "trời, bầu trời",
    "người nô lệ (đen & bóng)",
    "ngủ; giấc ngủ",
    "trượt, tuột, trôi qua, chạy qua",
    "chậm, chậm chạp",
    "nhỏ, bé",
    "ngửi; sự ngửi, khứu giác",
    "cười, mỉm cười; nụ cười, vẻ tươi cười",
    "tuyết; tuyết rơi",
    "như vậy, như thế; vì thế, vì vậy, vì thế cho nên",
    "mềm, dẻo",
    "đất trồng; vết bẩn",
    "lính, quân nhân",
    "sự giải quyết, giải pháp",
    "giải, giải thích, giải quyết",
    "một it, một vài",
    "con trai",
    "bài hát",
    "sớm, chẳng bao lâu nữa",
    "âm thanh; nghe",
    "phương Nam, hướng Nam; ở phía Nam; hướng về phía Nam",
    "khoảng trống, khoảng cách",
    "nói",
    "đặc biệt, riêng biệt",
    "sự nói, khả năng nói, lời nói, cách nói, bài nói",
    "tốc độ, vận tốc",
    "đánh vần; sự thu hút, sự quyến rũ, say mê",
    "tiêu, xài",
    "nói",
    "dấu, đốm, vết",
    "trải, căng ra, bày ra; truyền bá",
    "mùa xuân",
    "vuông, vuông vắn; dạng hình vuông, hình vuông",
    "đứng, sự đứng",
    "ngôi sao, dán sao, trang trí hình sao, đánh dấu sao",
    "bắt đầu, khởi động; sự bắt đầu, sự khởi đầu, khởi hành",
    "nhà nước, quốc gia, chính quyền; (thuộc) nhà nước, có liên quan đến nhà nước; phát biểu, tuyên bố",
    "trạm, điểm, đồn",
    "ở lại, lưu lại; sự ở lại, sự lưu lại",
    "có ích cho ai, có lợi cho ai; sẵn sàng giúp đỡ ai",
    "hơi nước",
    "thép, ngành thép",
    "bước; bước, bước đi",
    "đâm, thọc, chọc, cắm, dính; cái gậy, qua củi, cán",
    "đứng yên; vẫn, vẫn còn",
    "đá",
    "sự dừng lại, sự đứng lại",
    "dừng, ngừng, nghỉ, thôi; sự dừng, sự ngừng, sự đỗ lại",
    "cửa hàng, kho hàng; tích trữ, cho vào kho",
    "chuyện, câu chuyện",
    "thẳng, không cong",
    "xa lạ, chưa quen",
    "dòng suối",
    "phố, đườmg phố",
    "căng ra, duỗi ra, kéo dài ra",
    "dây, sợi dây",
    "khỏe, mạnh, bền, vững, chắc chắn",
    "sinh viên",
    "sự học tập, sự nghiên cứu; học tập, nghiên cứu",
    "chủ đề, đề tài; chủ ngữ",
    "chất liệu; bản chất; nội dung",
    "trừ",
    "sự thành công, sự thành đạt",
    "như thế, như vậy, như là",
    "thình lình, đột ngột",
    "hậu tố",
    "đường",
    "đề nghị, đề xuất; gợi",
    "bộ com lê, trang phục; thích hợp, quen, hợp với",
    "mùa hè",
    "mặt trời",
    "sự cung cấp, nguồn cung cấp; cung cấp, đáp ứng, tiếp tế",
    "sự chống đỡ, sự ủng hộ; chống đỡ, ủng hộ",
    "chắc chắn, xác thực",
    "mặt, bề mặt",
    "sự ngạc nhiên, sự bất ngờ; làm ngạc nhiên, gây bất ngờ",
    "bơi lội",
    "âm tiết",
    "biểu tượng, ký hiệu",
    "hệ thống, chế độ",
    "",
    "T",
    "cái bàn",
    "đuôi, đoạn cuối",
    "/teɪk/",
    "nói chuyện, trò chuyện; cuộc trò chuyện, cuộc thảo luận",
    "cao",
    "dạy",
    "đội, nhóm",
    "răng",
    "nói, nói với",
    "nhiệt độ",
    "mười, chục",
    "giới hạn, kỳ hạn, khóa, kỳ học",
    "bài kiểm tra, sự thử nghiệm, xét nghiệm; kiểm tra, xét nghiệm, thử nghiệm",
    "hơn",
    "cám ơn",
    "người ấy, đó, vật ấy, đó; rằng, là",
    "cái, con, người…",
    "của chúng, của chúng nó, của họ",
    "chúng, chúng nó, họ",
    "khi đó, lúc đó, tiếp đó",
    "ở nơi đó, tại nơi đó",
    "này",
    "chúng, chúng nó, họ; những cái ấy",
    "dày; đậm",
    "mỏng, mảnh",
    "cái, đồ, vật",
    "nghĩ, suy nghĩ",
    "thứ ba",
    "cái này, điều này, việc này",
    "Những, cái đó",
    "dù, dù cho, mặc dù; mặc dù, tuy nhiên, tuy vậy",
    "sự suy nghĩ, khả năng suy nghĩ; ý nghĩ, tư tưởng, tư duy",
    "nghìn",
    "ba",
    "qua, xuyên qua",
    "ném, vứt, quăng",
    "như vậy, như thế, do đó",
    "buộc, cột, trói; dây buộc, daay trói, dây giày",
    "thời gian, thì giờ",
    "rất nhỏ, nhỏ xíu",
    "làm mệt mỏi, trở nên mệt nhọc; lốp, vỏ xe",
    "theo hướng, tới",
    "cùng nhau, cùng với",
    "nói, nói với, nói lên, nói ra",
    "tiếng, giọng",
    "cũng",
    "sự cầm, sự nắm, sự lấy",
    "dụng cụ, đồ dùng",
    "chóp, đỉnh; đứng đầu, trên hết",
    "tổng cộng, toàn bộ; tổng số, toàn bộ số lượng",
    "sờ, mó, tiếp xúc; sự sờ, sự mó, sự tiếp xúc",
    "dễ bảo, dễ dạy, ngoan",
    "thị trấn, thị xã, thành phố nhỏ",
    "phần của đĩa; đường mòn, đường đua",
    "thương mại, buôn bán; buôn bán, trao đổi",
    "xe lửa, tàu hỏa; dạy, rèn luyện, đào tạo",
    "đi lại, đi du lịch, di chuyển; sự đi, những chuyến đi",
    "cây",
    "hình tam giác",
    "cuộc dạo chơi, cuộc du ngoạn; đi dạo, du ngoạn",
    "điều lo lắng, điều muộn phiền",
    "rau quả tươi",
    "đúng, thật",
    "thử, cố gắng",
    "ống, tuýp",
    "quay, xoay, vặn; sự quay, vòng quay",
    "hai mươi",
    "hai, đôi",
    "loại, kiểu, mẫu; phân loại, xếp loại",
    "",
    "U",
    "dưới, ở dưới; ở phía dưới, về phía dưới",
    "đơn vị",
    "trước khi, cho đến khi",
    "ở trên, lên trên, lên",
    "chúng tôi, chúng ta; tôi và anh",
    "sử dụng, dùng; sự dùng, sự sử dụng",
    "thông thường, thường dùng",
    "",
    "V",
    "thung lũng",
    "giá trị, ước tính, định giá",
    "thay đổi, làm cho khác nhau, biến đổi",
    "động từ",
    "rất, lắm",
    "sự nhìn, tầm nhìn; nhìn thấy, xem, quan sát",
    "làng, xã",
    "đi thăm hỏi, đến chơi, tham quan; sự đi thăm, sự thăm viếng",
    "tiếng, giọng nói",
    "nguyên âm",
    "",
    "W",
    "chờ đợi",
    "đi, đi bộ; sự đi bộ, sự đi dạo",
    "tường, vách",
    "muốn",
    "chiến tranh",
    "ấm, ấm áp; làm cho nóng, hâm nóng",
    "thì, là",
    "rửa, giặt",
    "nhìn, theo dõi, quan sát; sự canh gác, sự canh phòng",
    "nước",
    "sóng, gợn nước; gợn sóng, uốn thành sóng",
    "đường, đường đi",
    "chúng tôi, chúng ta",
    "mặc, mang, đeo",
    "thời tiết",
    "tuần, tuần lễ",
    "trọng lượng",
    "tốt, giỏi; ôi, may quá!",
    "đi",
    "thì, là",
    "phía Tây, theo phía tây, về hướng tây",
    "gì, thế nào",
    "bánh xe",
    "khi, lúc, vào lúc nào",
    "đâu, ở đâu; nơi mà",
    "có..không; có… chăng; không biết có.. không",
    "nào, bất cứ.. nào; ấy, đó",
    "trong lúc, trong khi; lúc, chốc, lát",
    "trắng; màu trắng",
    "ai, người nào, kẻ nào, người như thế nào",
    "bình an vô sự, không suy suyển, không hư hỏng; toàn bộ, tất cả, toàn thể",
    "của ai",
    "tại sao, vì sao",
    "rộng, rộng lớn",
    "vợ",
    "dại, hoang",
    "sẽ; ý chí, ý định",
    "chiếm, đọat, thu được",
    "gió",
    "cửa sổ",
    "cánh, sự bay, sự cất cánh",
    "mùa đông",
    "dây (kim loại)",
    "ước, mong muốn; sự mong ước, lòng mong muốn",
    "với, cùng",
    "đàn bà, phụ nữ",
    "Những người phụ nữ",
    "ngạc nhiên, lấy làm lạ, kinh ngạc",
    "Sẽ không",
    "gỗ",
    "từ",
    "làm việc, sự làm việc",
    "thế giới",
    "Sẽ",
    "viết",
    "viết ra, được thảo ra",
    "sai",
    "viết",
    "",
    "Y",
    "Iat, thước Anh (bằng 0, 914 mét), sân",
    "năm",
    "vàng",
    "vâng, phải, dạ, được, ừ, có, có chứ",
    "còn, hãy còn, còn nữa",
    "anh, chị, ông, bà, ngài, ngươi, mày; các anh, các chị, các ông, các bà, các ngài",
    "trẻ, trẻ tuổi, thiếu niên, thanh niên",
    "của anh, của chị, của ngài, của mày; của các anh, của các chị, của các ngài, của"
];
let eDataResult = []; // danh sách các từ tiếng anh tìm được
let eResultUs = document.querySelector('.result-us');
let eResultVn = document.querySelector('.result-vn');
eData.push('- hello');
vData.push('xin chào');


function nowTranslate(indexVData) {
    eResultVn.innerHTML = `<div class="group-translate-result">
                                <p>${vData[indexVData]}</p>
                           </div>`;
}

// removeExcessWord: loại bỏ dư thừa
// example: – able (adj) --> return: able
function removeExcessWord(word) {
    word = word.trim();
    let start = word.indexOf(' ');
    let end = word.indexOf(' ', start + 1);
    return word.slice(start , end).trim();
}
// trong danh sách các từ tiếng anh lọc ra các từ, có từ bắt đầu là từ khóa tìm kiếm
function filterByStartWidths(key, data) {
    let result = [];
    let newWord;
    for(let wordIndex in data) {
        newWord = removeExcessWord(data[wordIndex]);
        if(newWord.startsWith(key)) {
            let newWordObj = {};
            newWordObj.data = data[wordIndex];
            newWordObj.index = wordIndex;

            result.push(newWordObj);
        }
    }
    return result;
}

// in ra những từ tiếng anh có chứa từ khóa tìm kiếm
function render() {
    eDataResult = [];
    let englishInput = eEnglishInput.value;
    if(englishInput.length > 0) {
        eDataResult = filterByStartWidths(englishInput, eData);
        if(eDataResult.length > 0) {
            let source = '';
            for(let word of eDataResult) {
                source += `<div class="group-translate">
                                <p>${word.data}</p>
                                <input type="button" onclick="nowTranslate(${word.index})" id="btn-translate" value="Dịch">
                           </div>`;
            }
            document.getElementById('amount').innerText = eDataResult.length + ' Kết quả';
            eResultUs.innerHTML = source;
        } else {
            eResultUs.innerHTML = `<p>Không tìm thấy</p>`;

        }
    }

}

// eBtnTranslate.addEventListener('click', render);
eEnglishInput.addEventListener('keyup', render);
eEnglishInput.addEventListener('keydown', () =>{
    eResultUs.innerHTML = '';
});
